#GAEの基本情報
runtime: python38
instance_class: F1
env: standard
service: default
# プロジェクト名.GCE上 wsgi:application
entrypoint: gunicorn -b :$PORT config.wsgi:application

# 下記 includes で環境変数用のsecret.yamlファイルのpathを指定しています。
includes:
- secrets/secret.yaml

handlers:
  - url: /static
    static_dir: staticfiles/
  - url: .*
    secure: always
    script: auto